version: '3.1'

services:
  mongodb:
    image: mongo
    restart: always
    command: mongod --auth
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootroot
  mongo_seed:
    build: ./mongo
    depends_on:
      - mongodb
    links:
      - mongodb
  express:
    build: ./back
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    links:
      - mongodb
  app:
    build: ./front
    ports:
      - 80:80
    depends_on:
      - mongodb
    links:
      - mongodb